name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
      
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Maven Package API Gateway
        run: mvn -f ./services/gatewayapi/GatewayAPI/pom.xml -B clean package -DskipTests
        
      - name: Maven Package ReservationApplication
        run: mvn -f ./services/reservation_app/ReservationApplication/pom.xml -B clean package -DskipTests
        
      - name: Maven Package PaymentApplication
        run: mvn -f ./services/payment_app/PaymentApplication/pom.xml -B clean package -DskipTests
        
      - name: Maven Package LoyaltyApplication
        run: mvn -f ./services/loyalty_app/LoyaltyApplication/pom.xml -B clean package -DskipTests

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Wait 30s for App To Deploy
        run: sleep 30s
        shell: bash

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      # TODO setup variant, service and port

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v2
          SERVICE_NAME: loyalty
          PORT_NUMBER: 8050

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 3
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v